"""init_knowledge_tables

Revision ID: a8700bd8fe29
Revises: c85335cfecfd
Create Date: 2026-08-03 12:17:53.071727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8700bd8fe29'
down_revision: Union[str, None] = 'c85335cfecfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('parse_status', sa.String(length=20), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_files_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_files_scope'), ['scope'], unique=False)

    op.create_table('file_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['knowledge_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_chunks_file_id'), ['file_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_chunks_file_id'))

    op.drop_table('file_chunks')
    with op.batch_alter_table('knowledge_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_files_scope'))
        batch_op.drop_index(batch_op.f('ix_knowledge_files_owner_user_id'))

    op.drop_table('knowledge_files')
    # ### end Alembic commands ###
